#!/bin/bash

usage()
{
echo -e "\n    usage: \033[1m$0 filename version\033[0m"
cat << END_USAGE_TEXT

This file changes the line that contains the version of the 
suite in the license message. The version is replaced by
the one given in the command line.
"version" must have the format "X.Y.Z",
where X, Y, and Z are numbers.
   -h               Display the help menu.

END_USAGE_TEXT
}

if [ $# -lt 1 ]
then
   echo "Error: input filename missing (Try -h for more information.)."
   exit 2
fi

FILENAME=$1
VERSION=$2
OVERWRITE=true

while getopts ":ho:v:" opt; do
  case $opt in
    o)
      #echo "-o was triggered!"
      LICNAME=$OPTARG
      OVERWRITE=false
      ;;
    v)
      PRINTVERSION=true
      VERSION=$OPTARG
      ;;
    h)
      usage
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

shift $(($OPTIND - 1))

echo "name: $FILENAME"

TMPNAME=tmp${RANDOM}${RANDOM}

cat $FILENAME | sed "s/\(.*\)VERSION: \(.*\)/\1VERSION: $VERSION/g" $FILENAME > $TMPNAME
if [ "$OVERWRITE" == true ]; then
   mv $TMPNAME $FILENAME
   echo "this is were the file with the old version is overwritten..."
fi

