#!/bin/bash

usage()
{
echo -e "\n    usage: \033[1m$0 filename NEWVERSION\033[0m"
cat << END_USAGE_TEXT

This file changes the line that contains the CURRENTVERSION of the 
program. The CURRENTVERSION is replaced by
the NEWVERSION given in the command line.
"NEWVERSION" must have the format "X.Y.Zx",
where X, Y, and Z are numbers, and x may be a character, or 
nothing.
   -h               Display the help menu.

END_USAGE_TEXT
}

if [ $# -lt 1 ]
then
   echo "Error: input filename missing (Try -h for more information.)."
   exit 2
fi

FILENAME=$1
VERSION=$2
OVERWRITE=true

while getopts ":ho:v:" opt; do
  case $opt in
    o)
      #echo "-o was triggered!"
      LICNAME=$OPTARG
      OVERWRITE=false
      ;;
    v)
      PRINTVERSION=true
      VERSION=$OPTARG
      ;;
    h)
      usage
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

shift $(($OPTIND - 1))

#echo "name: $FILENAME"

TMPNAME=tmp${RANDOM}${RANDOM}

cat $FILENAME | sed "s/\(.*\)CURRENTVERSION \"\(.*\)\"/\1CURRENTVERSION \"$VERSION\"/" > $TMPNAME
if [ "$OVERWRITE" == true ]; then
   mv $TMPNAME $FILENAME
   #echo "this is were the file with the old version is overwritten..."
fi

