#!/bin/bash
thisScriptName=$(echo "$0" | sed -e 's;\(.*\)/\(.*\);\2;')
usage()
{
echo -e "\n    usage: \033[1m$1 [option [value(s)]] ... [option [value(s)]]\033[0m"
cat << END_USAGE_TEXT

This script computes the NCI field and makes two cubes, and one plot
(s vs rho), which can be used to refine the cubes (by selecting
appropriate cutoffs for rho and s). The script also generates
VMD scripts that automatically loads and visualizes the 
NCI index.

Options 
  -h           Displays the help menu.
  -w wf?name   Sets the wavefunction name to be 'wf?name' (wfxname/wfnname)
  -c "a1 a2"     Centres the cube to be at the midpoint between atoms a1 and
                 a2. Please mind the quotes to set a1 and a2.
  -P           Plot again the figures without re-computing cubes.
                 The option forces to skip cubes calculation without asking.
  -l        	Writes cpu time, input/output information etc. on a log file
  -n  dim   	Sets the number of points per direction for the cube
            	  to be dim x dim x dim.
  -s        	Uses a smart cuboid for the grid. The number of points for the
            	  largest direction will be 80.
  -S ln     	Uses a smart cuboid for the grid. ln is the number of points
            	  the largest axis will have. The remaining axes will have
            	  a number of points proportional to its length.
  -r rmin      Sets the lower rho cutoff to be rmin
  -R rmax      Sets the upper rho cutoff to be rmax
  -G smax      Sets the upper reduced density gradient (s) cutoff to be smax
  -q           Adds 'quiet' to the vmd script (closes vmd after rendering)


END_USAGE_TEXT
}
print_vmd_script()
{
   the_rho_file_name=$1
   the_red_grad_file_name=$2
   the_red_grad_value=$3
   the_rho_value=$4
   the_tga_file_name="$5"
cat << END_VMD_SCRIPT
#!/usr/local/bin/vmd

#VMD script written by save_state Revision: 1.41 $
#VMD version: 1.8.6
set viewplist
set fixedlist
# Display settings
display projection Orthographic
display nearclip set 0.000000
display depthcue Off
color Display Background white
axes location Off
# load new molecule
mol new $the_red_grad_file_name type cube first 0 last -1 step 1 filebonds 1 autobonds 1 waitfor all
mol addfile $the_rho_file_name type cube first 0 last -1 step 1 filebonds 1 autobonds 1 waitfor all
#
# representation of the atoms
mol delrep 0 top
mol representation CPK 1.000000 0.600000 118.000000 131.000000
mol color Name
mol selection {all}
mol material Opaque
mol addrep top
#
# add representation of the surface
mol representation Isosurface $the_red_grad_value 1 0 0 1 1
#The following line chooses the first (0) cube to be coloured with volume representation.
mol color Volume 0
mol selection {all}
mol material Opaque
mol addrep top
mol selupdate 1 top 0
mol colupdate 1 top 0
mol scaleminmax top 1 -$the_rho_value $the_rho_value
mol smoothrep top 1 0
mol drawframes top 1 {now}
color scale method RGB
set colorcmds {{color Name {C} gray}}
#some more

render TachyonInternal $the_tga_file_name

END_VMD_SCRIPT
}
#computes the cube files.
compute_cubes() {
   the_wf_file_name="$1"
   the_cube_args="$2"
   the_limits_of_compute_cubes="$3"
   echo "####################################"
   echo -e "\tStarting NCI cube evaluation"
   echo "####################################"
   #computes NCI--Rho
   launcher1="dtkcube $the_wf_file_name $the_cube_args -p z $the_limits_of_compute_cubes"
   echo $launcher1
   $launcher1
   #computes NCI--RedGrad
   launcher2="dtkcube $the_wf_file_name $the_cube_args -p Z $the_limits_of_compute_cubes"
   echo $launcher2
   $launcher2
}
#Prints all values of a cube as a single column
cube_to_column(){
   cube_file="$1"
   let number_of_atoms=$(sed -n '3p' "$cube_file"| awk '{print $1;}')+6
   awk '{if (NR>'$number_of_atoms'){print $0;}}' $cube_file | awk '$1=$1'|tr [:space:] "\n"
}
#Echoes terminal specific options for gnuplot
print_term_specific_conf(){
   lcl_datname="$1"
   the_terminal="$2"
   lcl_xlabel="{/Symbol L}_2"
   if [ "$the_terminal" == "pngcairo" ];then
      lcl_outputname="${lcl_datname%dat}png"
      terminal_string="term pngcairo enhanced interlace size 1200,900 linewidth 2 fontscale 1.5"
   elif [ "$the_terminal" == "png" ];then
      lcl_outputname="${lcl_datname%dat}png"
      terminal_string="term png enhanced interlace size 1200,900 linewidth 2 fontscale 1.5"
      lcl_xlabel="Lambda_2"
   elif [ "$the_terminal" == "jpg" ];then
      lcl_outputname="${lcl_datname%dat}jpg"
      terminal_string="term jpeg enhanced interlace size 1200,900 linewidth 2 fontscale 1.5"
      lcl_xlabel="Lambda_2"
   elif [ "$the_terminal" == "pdf" ];then
      lcl_outputname="|epstopdf --filter --outfile=${lcl_datname%dat}pdf"
      terminal_string="term postscript eps enhanced color linewidth 2 fontscale 1.5"
   fi
   echo "set encoding utf8"
   echo "set xlabel '$lcl_xlabel' offset character 0,0.75"
   echo "set ylabel 's' offset character 2,0"
   echo "set $terminal_string"
   echo "set output '$lcl_outputname'"
   echo "plot '$lcl_datname' u 1:2:1 w p pt 7 ps 0.25 palette title 'NCI'"
}
#Makes a plot using gnuplot
make_plot(){
   dat_file_name=$1
   gnp_file_name=${dat_file_name%dat}gnp
   png_file_name=${dat_file_name%dat}png
   cat > $gnp_file_name <<-EOFMarker
set xrange [-0.2:0.2]
set yrange [0.0:2.0]
set cbrange [-0.2:0.2]
set xtics 0.05
set ytics 0.2
set mxtics 5
set mytics 2
set grid ytics mytics
set grid xtics mxtics
set palette rgbformulae 33,13,10
set tmargin at screen 0.95
set bmargin at screen 0.13
set lmargin at screen 0.10
set rmargin at screen 0.84
EOFMarker
print_term_specific_conf $dat_file_name $gnuplotTerminal >> $gnp_file_name
gnuplot $gnp_file_name
}
#Makes a plot of GrdRedRho vs Rho
plot_redgradrho_vs_rho() {
   data_cube_RedDensGrad="$1"
   data_cube_Rho="$2"
   data_plot_NCI="${3}NCISvsRho.dat"
   tmp_dat_rho_file=${RANDOM}${RANDOM}
   tmp_dat_s_file=${RANDOM}${RANDOM}
   cube_to_column $data_cube_Rho > $tmp_dat_rho_file
   cube_to_column $data_cube_RedDensGrad > $tmp_dat_s_file
   paste $tmp_dat_s_file $tmp_dat_rho_file > $data_plot_NCI 
   rm $tmp_dat_rho_file; rm $tmp_dat_s_file
   make_plot $data_plot_NCI
}

if [ $# -lt 1 ]
then
   echo -e "\033[1m\033[31mError:\033[0m Invalid syntax! (Try $thisScriptName -h for more information.)."
   exit 2
fi

cubeArgsString=""
# Default values for limits of cubes to be will compute
rhoMin="0.0005"
rhoMax="0.2"
redDensGradMax="2.0"
quietVMDRendering=false
askCubeComputation=true
gnuplotTerminal="pngcairo"
while getopts ":hw:ln:Pr:R:sS:t:G:c:q" opt; do
  case $opt in
    h)
      usage $0
      exit 0
      ;;
    w)
      wavefunctionFileName="$OPTARG"
      ;;
    c)
      cubeArgsString="$cubeArgsString -c $OPTARG"
      ;;
    l)
      cubeArgsString="$cubeArgsString -l"
      ;;
    n)
      cubeArgsString="$cubeArgsString -n $OPTARG"
      ;;
    P)
      askCubeComputation=false
      ;;
    r)
      rhoMin="$OPTARG"
      ;;
    R)
      rhoMax="$OPTARG"
      ;;
    s)
       cubeArgsString="$cubeArgsString -s"
      ;;
    S)
      cubeArgsString="$cubeArgsString -S $OPTARG"
      ;;
    t)
      gnuplotTerminal="$OPTARG"
      ;;
    G)
      redDensGradMax="$OPTARG"
      ;;
    q)
      quietVMDRendering=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      echo -e "(Try\n   $thisScriptName -h\nfor more information.)"
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$wavefunctionFileName" ]
then
   echo -e "\033[1m\033[31mError:\033[0m Wavefuntion file name missing" 
   echo -e "\tTry \n\t\t$thisScriptName -h\n\tfor more information."
   exit 2
fi

cutoffArgString="--configure-nci $rhoMin $rhoMax $redDensGradMax"

#This final extension was acquired from scr/common/fldtypesdef.h file of the function getFieldTypeKeyShort
baseFileName=${wavefunctionFileName%.wf?}
cubeRedGradFileName="${baseFileName}NCIRedDensGrad.cub"
cubeRhoFileName="${baseFileName}NCILambda2.cub"

#Checks whether cubes are present.
if [ "$askCubeComputation" = true ]; then
   if [ -f "$cubeRedGradFileName" -a -f "$cubeRhoFileName" ]; then
      echo -e "The needed cube files are already present ($cubeRedGradFileName and $cubeRhoFileName)"
      echo "Do you wish to compute them again?"
      select answer in "Yes=1" "No=2"
      do
         case $answer in
            Yes=1 )
               compute_cubes "$wavefunctionFileName" "$cubeArgsString" "$cutoffArgString"
               break;;
            No=2 )
               echo -e "Skipping cube calculation...\n"
               break;;
         esac
      done
   else
      compute_cubes "$wavefunctionFileName" "$cubeArgsString" "$cutoffArgString"
   fi
fi
#
#Names of VMD script files
#outputVMDFileName="${baseFileName}NCI.vmd"
#outputTGAFileName="${baseFileName}NCI.tga"
#Asks and saves the current directory (VMD sometimes needs absolute paths)
currentWD=$(pwd)
#
#Makes the VMD scripts.
#echo -e "Making VMD scripts..."
#print_vmd_script "$cubeRhoFileName" "$cubeRedGradFileName" 0.500000 0.050000 "$outputTGAFileName" > "$outputVMDFileName"
#if [ "$quietVMDRendering" = true ]; then
#   echo "quit" >> "$outputVMDFileName"
#fi

echo -e "Making s vs rho plot..."
plot_redgradrho_vs_rho "$currentWD/$cubeRhoFileName" "$currentWD/$cubeRedGradFileName" "$currentWD/$baseFileName"

