#!/bin/bash
#
#*****************************************************************************************
#*****************************************************************************************
#The following part checks the existence of several programs needed for the proper running
# of the suite denstoolkit.
#*****************************************************************************************
# 
have_gnuplot=1
if command -v gnuplot >/dev/null 2>&1 || command -v wgnuplot >/dev/null 2>&1; then
        echo -e "We have gnuplot!\033[33m"
        #echo -e "\033[33m"
        echo "However, please ensure that the x11 terminal is available."
        echo -e "\033[m"
        have_gnuplot=0
   else
        echo -e "\033[31m"
        echo -e "\nError: gnuplot must be installed in your system!\n"
        echo -e "\033[m"
fi
#
have_epstool=1
if command -v epstool >/dev/null 2>&1; then
	echo "We have epstool!"
   have_epstool=0
   else
        echo -e "\033[31m"
	echo -e "\nError: epstool must be installed in your system!\n"
        echo -e "\033[m"
fi
#
have_epstopdf=1
if command -v epstopdf >/dev/null 2>&1; then
	echo "We have epstopdf!"
   have_epstopdf=0
   else
        echo -e "\033[31m"
	echo -e "\nError: epstopdf must be installed in your system!\n"
        echo -e "\033[m"
fi
#
have_povray=1
if command -v povray >/dev/null 2>&1 || command -v pvengine64.exe >/dev/null 2>&1 \
    || command -v pvengine.exe >/dev/null 2>&1; then
	echo "We have povray!"
   have_povray=0
   else
        echo -e "\033[31m"
	echo -e "\nError: povray must be installed in your system!\n"
        echo -e "\033[m"
fi
#
have_graphicsmagick=1
if command -v gm >/dev/null 2>&1; then
	echo "We have gm!"
   have_graphicsmagick=0
   else
        echo -e "\033[31m"
	echo -e "\nError: gm must be installed in your system!\n"
        echo -e "\033[m"
fi
#
have_gzip=1
if command -v gzip >/dev/null 2>&1; then
	echo "We have gzip!"
   have_gzip=0
   else
      echo -e "\033[31m"
      echo -e "\nError: gzip must be installed in your system!\n"
      echo -e "\033[m"
fi
have_all=$(($have_gnuplot + $have_epstool + $have_epstopdf + $have_povray\
   + $have_graphicsmagick + $have_gzip))
echo -e "have_all=$have_all"
if [[ $have_all -gt "0" ]];then
      echo -e "\033[31m"
      echo -e "\nError: Some of the packages are not installed in your system!\n"
      echo -e "       Please install them befor compiling DTK.\n"
      echo -e "\033[m"
fi
echo -e "\033[32m"
echo -e "\nAll required packages are installed, you can proceed to"
echo -e "build and install denstoolkit!\n"
echo -e "\033[m"
#*****************************************************************************************
#*****************************************************************************************
