#!/bin/bash
cd /Users/jmsolano/Documents/LongRun/proj/readwfn/src
DTKDIR=/Users/jmsolano/Documents/LongRun/proj/denstoolkit
WFDIR=/Users/jmsolano/Documents/LongRun/proj/readwfn/wavefiles
RELDIR=$DTKDIR/releases
#
cp dtkpoint/*.cpp $DTKDIR/src/dtkpoint
cp dtkpoint/*.h $DTKDIR/src/dtkpoint
cp dtkpoint/ChangeLog $DTKDIR/src/dtkpoint
cp dtkpoint/Makefile $DTKDIR/src/dtkpoint
#
cp dtkline/*.cpp $DTKDIR/src/dtkline
cp dtkline/*.h $DTKDIR/src/dtkline
cp dtkline/ChangeLog $DTKDIR/src/dtkline
cp dtkline/Makefile $DTKDIR/src/dtkline
#
cp dtkplane/*.cpp $DTKDIR/src/dtkplane
cp dtkplane/*.h $DTKDIR/src/dtkplane
cp dtkplane/ChangeLog $DTKDIR/src/dtkplane
cp dtkplane/Makefile $DTKDIR/src/dtkplane
#
cp dtkcube/*.cpp $DTKDIR/src/dtkcube
cp dtkcube/*.h $DTKDIR/src/dtkcube
cp dtkcube/ChangeLog $DTKDIR/src/dtkcube
cp dtkcube/Makefile $DTKDIR/src/dtkcube
#
cp dtkfindcp/*.cpp $DTKDIR/src/dtkfindcp
cp dtkfindcp/*.h $DTKDIR/src/dtkfindcp
cp dtkfindcp/ChangeLog $DTKDIR/src/dtkfindcp
cp dtkfindcp/Makefile $DTKDIR/src/dtkfindcp
#
cp dtkmomd/*.cpp $DTKDIR/src/dtkmomd
cp dtkmomd/*.h $DTKDIR/src/dtkmomd
cp dtkmomd/ChangeLog $DTKDIR/src/dtkmomd
cp dtkmomd/Makefile $DTKDIR/src/dtkmomd
#
cp dtkqdmol/*.cpp $DTKDIR/src/dtkqdmol
cp dtkqdmol/*.h $DTKDIR/src/dtkqdmol
cp dtkqdmol/ChangeLog $DTKDIR/src/dtkqdmol
cp dtkqdmol/Makefile $DTKDIR/src/dtkqdmol
#
cp dtkdemat1/*.cpp $DTKDIR/src/dtkdemat1
cp dtkdemat1/*.h $DTKDIR/src/dtkdemat1
cp dtkdemat1/ChangeLog $DTKDIR/src/dtkdemat1
cp dtkdemat1/Makefile $DTKDIR/src/dtkdemat1
#
cp dtkbpdens/*.cpp $DTKDIR/src/dtkbpdens
cp dtkbpdens/*.h $DTKDIR/src/dtkbpdens
cp dtkbpdens/ChangeLog $DTKDIR/src/dtkbpdens
cp dtkbpdens/Makefile $DTKDIR/src/dtkbpdens
#
cp common/*.cpp $DTKDIR/src/common
cp common/*.h $DTKDIR/src/common
cp $WFDIR/*.wf? $DTKDIR/wavefiles
#
cp ../tex/dtkmanual/dtk-manual.pdf $DTKDIR/docs
#
# DO NOT FORGET TO ADD THE NEW FILES TO THE TAR FILE.
#
cp MakefileDist $DTKDIR/src/Makefile
cp checkdependencies $DTKDIR/src/checkdependencies
cp scripts/dtkeps2pdf $DTKDIR/src/scripts/dtkeps2pdf
cp scripts/dtkpov2png $DTKDIR/src/scripts/dtkpov2png
#
cd $DTKDIR
tmptarname="$RELDIR/denstoolkit-"$(date "+%Y%m%d-%H%M")".tar"
tar cvf $tmptarname src/dtkpoint/ src/dtkline/ src/dtkplane/ src/dtkcube/ \
  src/dtkfindcp/ src/dtkmomd  src/common/ src/dtkqdmol/ src/dtkdemat1 \
  src/dtkbpdens/ \
  wavefiles/ src/objs/ outputs/ bin/ docs/ src/Makefile src/checkdependencies src/scripts/
gzip -9 $tmptarname
