#!/bin/bash

SRC_DIR=$(pwd)
TOP_DIR=$SRC_DIR/..
SCRIPT_DIR=$SRC_DIR/scripts
TEX_DIR=$TOP_DIR/tex/dtkmanual
SOURCES=$(ls $SRC_DIR/dtk*/*.h $SRC_DIR/dtk*/*.cpp $SRC_DIR/common/*.h\
          $SRC_DIR/common/*.cpp $SRC_DIR/common/*.cxx $SRC_DIR/dtk*/*.cc \
          | sed '/eig2/d')
TEXES=$(ls $TEX_DIR/*.tex | sed '/hmdtk/d')

#SOLDEFINES=$(ls $SRC_DIR/dtk*/localdefs.h)

ADDGPL=$SCRIPT_DIR/dtkaddGPLv3
RMGPL=$SCRIPT_DIR/dtkrmGPLv3

ADDFDL=$SCRIPT_DIR/dtkaddfdl
RMFDL=$SCRIPT_DIR/dtkrmfdl

for i in $SOURCES; do
   echo "$RMGPL -v $(cat VERSION) $i"
   $RMGPL -v $(cat VERSION) $i
   echo "$ADDGPL -v $(cat VERSION) $i"
   $ADDGPL -v $(cat VERSION) $i
   echo "$SCRIPT_DIR/dtkchgsuiteversion $i $(cat VERSION)"
   $SCRIPT_DIR/dtkchgsuiteversion $i $(cat VERSION)
done

#for i in $SOLDEFINES; do
#   echo "$RMGPL -v $(cat VERSION) $i"
#   $RMGPL -v $(cat VERSION) $i
#   echo "$ADDGPL -v $(cat VERSION) $i"
#   $ADDGPL -v $(cat VERSION) $i
#   echo "$SCRIPT_DIR/dtkchgcurrversion $i $(cat VERSION)"
#   $SCRIPT_DIR/dtkchgcurrversion $i $(cat VERSION)
#done

for i in $TEXES; do
   echo "$RMFDL -v $(cat VERSION) $i"
   $RMFDL -v $(cat VERSION) $i
   echo "$ADDFDL -v $(cat VERSION) $i"
   $ADDFDL -v $(cat VERSION) $i
   echo "$SCRIPT_DIR/dtkchgsuiteversion $i $(cat VERSION)"
   $SCRIPT_DIR/dtkchgsuiteversion $i $(cat VERSION)
done


